# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Calvo's learning
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
      scheme: slate
  features:
    - navigation.tabs
    - navigation.indexes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
